#!/usr/bin/env bash
#A script that displays HI and Best School at 9th iteration

count=1

while [ $count -le 10 ]
do
   if [ $count -eq 9 ]
     then
     echo "Best School"
     echo "Hi"
   else
     echo "Best School"
   fi
   ((count++))
done 
