#!/usr/bin/env bash
#A script that displays 1 - 20
#Displays 4 and bad luck from China for iteration 4
#Displays 9 bad luck from Japan for iteration 9
#Displays 17 and bad luck from Italy for iteration 17

i=1

while [ $i -le 20 ]
do
	echo "$i"
	case $i in
	    "4") echo "bad luck from China";;
	    "9") echo "bad luck from Japan";;
	    "17") echo "bad luck from Italy";;
	esac
	(( i++ ))
done
